# Practice reshape

In [2]:
#https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html
import numpy as np

a = np.zeros((10, 2))
a.view()

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [5]:
b=a.T # A transpose make the array non-contiguous
b.view()

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [6]:
c=b.view()# Taking a view makes it possible to modify the shape without modifying the initial object.
c.shape=(20)

AttributeError: incompatible shape for a non-contiguous array

In [7]:
a = np.arange(6).reshape((3, 2))
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [8]:
np.reshape(a, (2, 3)) # C-like index ordering

array([[0, 1, 2],
       [3, 4, 5]])

In [11]:
a=np.array([[1,2,3],[4,5,6]])
np.reshape(a,6)

array([1, 2, 3, 4, 5, 6])

In [12]:
np.reshape(a,(1,6))

array([[1, 2, 3, 4, 5, 6]])

In [13]:
np.reshape(a,(6,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [14]:
np.reshape(a,(3,-1))

array([[1, 2],
       [3, 4],
       [5, 6]])

# Numpy where

In [25]:
np.where([[True, False], [True, True]],[[1, 2], [3, 4]],[[9, 8], [7, 6]])
#???????????????

array([[1, 8],
       [3, 4]])

In [16]:
#[xv if c else yv for (c,xv,yv) in zip(condition,x,y)]
np.where([[0, 1], [1, 0]])

(array([0, 1]), array([1, 0]))

In [19]:
x = np.arange(9.).reshape(3, 3)
x.view()

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]])

In [20]:
np.where( x > 5 ) #???????????????:#If only condition is given, return the tuple condition.nonzero(), the indices where condition is True.

(array([2, 2, 2]), array([0, 1, 2]))

In [21]:
x[np.where( x > 3.0 )]               # Note: result is 1D.

array([ 4.,  5.,  6.,  7.,  8.])

In [22]:
np.where(x < 5, x, -1)               # Note: broadcasting.

array([[ 0.,  1.,  2.],
       [ 3.,  4., -1.],
       [-1., -1., -1.]])

In [23]:
goodvalues = [3, 4, 7]
ix = np.in1d(x.ravel(), goodvalues).reshape(x.shape)
ix

array([[False, False, False],
       [ True,  True, False],
       [False,  True, False]], dtype=bool)

In [24]:
np.where(ix) #If only condition is given, return the tuple condition.nonzero(), the indices where condition is True.

(array([1, 1, 2]), array([0, 1, 1]))

In [26]:
x.ravel()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.])

In [27]:
x.nonzero()

(array([0, 0, 1, 1, 1, 2, 2, 2]), array([1, 2, 0, 1, 2, 0, 1, 2]))

In [28]:
x

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]])

In [29]:
y= np.eye(3)
y


array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [30]:
np.nonzero(y)

(array([0, 1, 2]), array([0, 1, 2]))

# List.extend

In [31]:
x = [1, 2, 3]
x.append([4, 5]) #Appends object at end.
print (x)

[1, 2, 3, [4, 5]]


In [32]:
x = [1, 2, 3]
x.extend([4, 5]) #Extends list by appending elements from the iterable.
print (x) 

[1, 2, 3, 4, 5]


# numpyarray.tolist()


In [33]:
a = np.array([1, 2])
a.view()

array([1, 2])

In [34]:
a.tolist()

[1, 2]

In [35]:
a = np.array([[1, 2], [3, 4]])
print a

[[1 2]
 [3 4]]


In [36]:
list(a)

[array([1, 2]), array([3, 4])]

In [40]:
c=list(a)
c.view()

AttributeError: 'list' object has no attribute 'view'

In [37]:
a.view()

array([[1, 2],
       [3, 4]])

In [38]:
a.tolist()

[[1, 2], [3, 4]]

In [39]:
a.tolist().view()

AttributeError: 'list' object has no attribute 'view'

# numpy.concatenate
https://docs.scipy.org/doc/numpy/reference/generated/numpy.concatenate.html

In [41]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)





array([[1, 2],
       [3, 4],
       [5, 6]])

In [43]:
b.T

array([[5],
       [6]])

In [42]:
np.concatenate((a, b.T), axis=1)



array([[1, 2, 5],
       [3, 4, 6]])

# random shuffle

random.shuffle(x[, random])
Shuffle the sequence x in place. The optional argument random is a 0-argument function returning a random float in [0.0, 1.0); by default, this is the function random().

Note that for even rather small len(x), the total number of permutations of x is larger than the period of most random number generators; this implies that most permutations of a long sequence can never be generated.